In [221]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [222]:
tf.__version__

'2.10.0'

In [223]:
relative_path = "../Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv"
data = pd.read_csv(relative_path)

In [224]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

task: remove the irrelevant column/s and the dependent variables

In [225]:
x = data.iloc[:, 3:13] # taking rownumber and customer suername out

In [ ]:
x

In [226]:
y = data['Exited']

In [ ]:
y

In [227]:
from sklearn.preprocessing import LabelEncoder

I can change the code the way I like.
learned about colum transformer and onehotencoder

In [228]:
le = LabelEncoder
x.Gender = LabelEncoder().fit_transform(x.Gender)

In [229]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [230]:
x = np.array(ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough').fit_transform(x))

In [231]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [232]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

for x_test, the code didn't accept the transform verson, therefore, I used fit-transform

In [233]:
from sklearn.preprocessing import StandardScaler
x_train = StandardScaler().fit_transform(x_train)
x_test = StandardScaler().fit_transform(x_test)

Part 2 : building the ANN
use control + p for seeing the paramters

In [234]:
ann = tf.keras.models.Sequential()

adding input hidden layers

In [235]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

adding one more hidden layers

In [236]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

adding the output layer

In [237]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

Training ANN

In [238]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN

In [239]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 1ms/step - loss: 0.5460 - accuracy: 0.7406
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4614 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4431 - accuracy: 0.7959
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4340 - accuracy: 0.7959
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4275 - accuracy: 0.7962
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4213 - accuracy: 0.7971
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4143 - accuracy: 0.8070
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4085 - accuracy: 0.8150
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4038 - accuracy: 0.8196
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4003 - accura


for the prediction always use double baracket

In [241]:
print(ann.predict(StandardScaler().fit_transform([[1,0,0,600,1,40,3,60000,2, 1,1,50000]])))

1/1 [==============================] - 0s 32ms/step
[[0.21190816]]


In [260]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5 )
# np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

63/63 [==============================] - 0s 933us/step


In [270]:
# type(y_pred)
y_pred = LabelEncoder().fit_transform(y_pred)

In [271]:
# y_test
# y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [280]:
# type(y_test)
# type(y_pred)
f'the type of y-test is {type(y_test)} and the type of y_pred is {type(y_pred)}'

"the type of y-test is <class 'numpy.ndarray'> and the type of y_pred is<class 'numpy.ndarray'>"

In [311]:
pred_matrix =  np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

In [312]:
pred_matrix = pd.DataFrame(pred_matrix)

In [313]:
type(pred_matrix)

pandas.core.frame.DataFrame

In [309]:
# pred_matrix.rename(columns= {"0":"Prediction", "1":"result"}, inplace=True)

In [314]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_pred, y_test)

array([[1514,  198],
       [  81,  207]], dtype=int64)

In [315]:
accuracy_score(y_pred, y_test)

0.8605